[tool.poetry]
name = "emoles"
version = "0.1.0"
license = "LGPL-3.0"
description = "Density-matrix electronic-structure models for electrolyte descriptors."
readme = "README.md"
repository = "https://github.com/Franklalalala/EMolES"
packages = [
    { include = "emoles" },
    { include = "dptb" }
]
include = [
    "emoles/**/*.pt",
    "emoles/**/*.pth"
]

[tool.poetry.dependencies]
python = ">=3.9, <=3.12.9"
numpy = "*"
scipy = "*"
spglib = "*"
matplotlib = "*"
ase = "*"
pyyaml = "*"
future = "*"
dargs = "0.4.4"
xitorch = "0.3.0"
e3nn = ">=0.5.1"
torch-runstats = "0.2.0"
opt-einsum = "3.3.0"
h5py = ">=3.7.0,<=3.11.0,!=3.10.0"
lmdb = "1.4.1"
tensorboard = "*"
pandas = "*"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.2.0"

[tool.poetry.scripts]
emoles = "emoles.__main__:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
